### PR TITLE
Fix allow_tags_with_style_attributes

### LINKED ISSUE #60: Error when using the `allow_tags_with_style_attributes` macro
When I make use of the `Meta.allow_tags_with_style_attributes` macro in my custom scrubber, I get this error message when I try to compile:

```
== Compilation error in file lib/testing_elixir_deps.ex ==
** (CompileError) lib/testing_elixir_deps.ex:59: undefined function scrub_css/1 (expected TestingElixirDeps.MyScrubber to define such a function or for it to be imported, but none are available)

** (exit) shutdown: 1
    (mix 1.14.0) lib/mix/tasks/compile.all.ex:78: Mix.Tasks.Compile.All.compile/4
    (mix 1.14.0) lib/mix/tasks/compile.all.ex:59: Mix.Tasks.Compile.All.with_logger_app/2
    (mix 1.14.0) lib/mix/tasks/compile.all.ex:33: Mix.Tasks.Compile.All.run/1
    (mix 1.14.0) lib/mix/task.ex:421: anonymous fn/3 in Mix.Task.run_task/4
    (mix 1.14.0) lib/mix/tasks/compile.ex:134: Mix.Tasks.Compile.run/1
    (mix 1.14.0) lib/mix/task.ex:421: anonymous fn/3 in Mix.Task.run_task/4
    (iex 1.14.0) lib/iex/helpers.ex:108: IEx.Helpers.recompile/1
    iex:17: (file)
```

Here's the code for the custom scrubber I wrote:
```
  defmodule MyScrubber do
    require HtmlSanitizeEx.Scrubber.Meta
    alias HtmlSanitizeEx.Scrubber.Meta

    # Removes any CDATA tags before the traverser/scrubber runs.
    Meta.remove_cdata_sections_before_scrub()
    Meta.strip_comments()

    Meta.allow_tags_with_style_attributes(["p", "span", "html", "body"])
    Meta.allow_tags_and_scrub_their_attributes(["b", "i"])

    Meta.strip_everything_not_covered()
  end
```

You can reproduce the error by creating and using a custom scrubber with the `Meta.allow_tags_with_style_attributes` macro.

### PR DESCRIPTION
**Pull request by rukykf**
closes https://github.com/rrrene/html_sanitize_ex/issues/60

### CODE REVIEW

**Comment by rrrene** [comment]
I am not sure what this PR does. 🤔 

The only change to library code is the change to `lib/html_sanitize_ex/scrubber/meta.ex`:

image

and I am pretty sure this is just formatting?

Two other things that stood out: Why would you rewrite a README and change its formatting in a PR that is supposed to fix an issue? And worse: Why would you change an existing test that is testing existing behaviour unaffected by the reported issue?

**Comment by rukykf** [comment]
@rrrene The change in formatting was not intentional. I did not pay attention to it before creating the PR. Sorry about that. I can fix it.

I changed the README because following the instructions in the README as it was prior, would not indicate to a reader how to use the `Meta.allow_tags_with_style_attributes` macro properly.  

Specifically, in the README before the change, it seemed like it would just be sufficient to use

`Meta.allow_tags_with_style_attributes`

To allow a tag with style properties.

But that's not the case. It took me some time to figure out that in addition to using `Meta.allow_tags_with_style_attributes(["p"])`, I was also supposed to use `Meta.allow_tags_and_scrub_their_attributes(["p"])`. I observed similar behavior for `Meta.allow_tag_with_uri_attributes("a", ["href"], ["https", "mailto"])`.

The change in the README adds the `Meta.allow_tags_and_scrub_their_attributes(["a", "p"])` to the custom scrubber example in the README to make it more explicit that that's how to use these 2 macros. Unless this is somehow not the intended behavior of the libraries.

I changed the scrubber test because it didn't seem to be validating that style attributes were actually allowed in the `input`.

This is the original input in the first test case: ` "<section><header><script>code!</script></header><p>hello <script>code!</script></p></section>"`, there's no style attributes in there despite the presence of ` Meta.allow_tags_with_style_attributes(["span", "html", "body"])` in the custom scrubber. You added this line to the test scrubber to allow tags with style attributes along with other changes in the commit you pushed to master that introduced the fix for the issue I originally reported.
I thought the test would be better if there was an actual style attribute in the test input.

**Comment by rrrene** [comment]
So this PR does not add or change any functionality? 

I am not trying to be difficult, just want to understand what this PR does. After all, it is called "Fix allow_tags_with_style_attributes".

**Comment by rukykf** [comment]
No, it does not add or change functionality. I can see how the title of the PR is misleading and I can always change it.

**Comment by rrrene** [comment]
I am closing this since it does not fix the referenced issue.

**Pull request closed without merging**
